// global
import ThemeConfig from '../theme'
import GlobalStyles from '../theme/globalStyles'
import ScrollToTop from '../components/ScrollToTop'
import { BaseOptionChartStyle } from '../components/charts/BaseOptionChart'
import DashboardLayout from '../layouts/dashboard'

import type { AppProps } from 'next/app'
import Head from 'next/head'
// import Nav from '../components/nav'
// import Header from '../components/header'
// import Footer from '../components/footer'
const App = ({ Component, pageProps }: AppProps) => {
  return (
    <ThemeConfig>
      <Head>
        <title>UniPass BOT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalStyles />
      <ScrollToTop />
      <BaseOptionChartStyle />
      <DashboardLayout>
        <Component {...pageProps} />
      </DashboardLayout>
      {/* <Nav />
      <main>
        <Header />
        <div className="page">
          <Component {...pageProps} />
        </div>
        <Footer />
      </main> */}
    </ThemeConfig>
  )
}

export default App
