// global
import './_app.scss'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import Nav from '../components/nav'
import Header from '../components/header'
import Footer from '../components/footer'
const App = ({ Component, pageProps }: AppProps) => {
  return (
    <div id="app">
      <Head>
        <title>UniPass BOT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main>
        <Header />
        <div className="page">
          <Component {...pageProps} />
        </div>
        <Footer />
      </main>
    </div>
  )
}

export default App
